In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('D:\\Code\\GlobalCommodity\\CSV Dataset\\commodity_trade_statistics_data.csv')
df.head()

C:\Users\praka\AppData\Local\Temp\ipykernel_29108\4010570921.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('D:\\Code\\GlobalCommodity\\CSV Dataset\\commodity_trade_statistics_data.csv')

,country_or_area,year,comm_code,commodity,flow,trade_usd,weight_kg,quantity_name,quantity,category
0,Afghanistan,2016,10410,"Sheep, live",Export,6088,2339.0,Number of items,51.0,01_live_animals
1,Afghanistan,2016,10420,"Goats, live",Export,3958,984.0,Number of items,53.0,01_live_animals
2,Afghanistan,2008,10210,"Bovine animals, live pure-bred breeding",Import,1026804,272.0,Number of items,3769.0,01_live_animals
3,Albania,2016,10290,"Bovine animals, live, except pure-bred breeding",Import,2414533,1114023.0,Number of items,6853.0,01_live_animals
4,Albania,2016,10392,"Swine, live except pure-bred breeding > 50 kg",Import,14265937,9484953.0,Number of items,96040.0,01_live_animals

In [4]:
df.describe()

               year     trade_usd     weight_kg      quantity
count  8.225871e+06  8.225871e+06  8.097396e+06  7.921014e+06
mean   2.004768e+03  9.505370e+07  3.556503e+07  2.671470e+08
std    7.037779e+00  7.074154e+09  2.479277e+09  3.739231e+11
min    1.988000e+03  1.000000e+00  0.000000e+00  0.000000e+00
25%    1.999000e+03  1.107200e+04  1.089000e+03  1.062000e+03
50%    2.005000e+03  1.534160e+05  2.689800e+04  2.712000e+04
75%    2.011000e+03  1.895476e+06  4.474432e+05  4.623620e+05
max    2.016000e+03  2.443311e+12  1.860133e+12  1.026357e+15